const AllRechargePlans = [
    {
      id: '1',
      title: 'Basic Plan',
      price: 75,
      data: '0.5GB/day',
      validity: '28 days',
      voiceCalls: 'Unlimited',
      sms: 'Limited',
      specialNote: 'Designed for JioPhone users.',
      dataBonus: '5GB bonus on first recharge',
      internationalCalls: 'Limited to 100 minutes',
      specialFeatures: 'Suitable for occasional users',
    },
    {
      id: '2',
      title: 'Standard Plan',
      price: 150,
      data: '1GB/day',
      validity: '28 days',
      voiceCalls: 'Unlimited',
      sms: 'Unlimited',
      specialNote: 'Best for regular users.',
      dataBonus: '10GB bonus on first recharge',
      internationalCalls: 'Unlimited to select countries',
      specialFeatures: 'Ideal for regular streaming',
    },
    {
      id: '3',
      title: 'Premium Plan',
      price: 300,
      data: '2GB/day',
      validity: '30 days',
      voiceCalls: 'Unlimited',
      sms: 'Unlimited',
      specialNote: 'Ideal for heavy users.',
      dataBonus: '15GB bonus on first recharge',
      internationalCalls: 'Unlimited to select countries',
      specialFeatures: 'Perfect for gamers and streamers',
    },
    {
      id: '4',
      title: 'Family Plan',
      price: 500,
      data: '5GB/day',
      validity: '30 days',
      voiceCalls: 'Unlimited',
      sms: 'Unlimited',
      specialNote: 'Shared among up to 4 family members.',
      dataBonus: '20GB bonus on first recharge',
      internationalCalls: 'Unlimited to select countries',
      specialFeatures: 'Great for families with high data usage',
    },
    {
      id: '5',
      title: 'Student Plan',
      price: 199,
      data: '1.5GB/day',
      validity: '84 days',
      voiceCalls: 'Unlimited',
      sms: 'Unlimited',
      specialNote: 'Exclusive for students with valid ID.',
      dataBonus: '5GB bonus on first recharge',
      internationalCalls: 'Limited to 50 minutes',
      specialFeatures: 'Designed for students who study online',
    },
    {
      id: '6',
      title: 'Unlimited Plan',
      price: 999,
      data: 'Unlimited',
      validity: '30 days',
      voiceCalls: 'Unlimited',
      sms: 'Unlimited',
      specialNote: 'Truly unlimited usage.',
      dataBonus: 'No bonus applicable',
      internationalCalls: 'Unlimited to select countries',
      specialFeatures: 'Ideal for heavy data users',
    },
    {
      id: '7',
      title: 'Weekend Plan',
      price: 100,
      data: '2GB',
      validity: '7 days',
      voiceCalls: 'Unlimited',
      sms: 'Unlimited',
      specialNote: 'Best for weekend travelers.',
      dataBonus: 'No bonus applicable',
      internationalCalls: 'Limited to 30 minutes',
      specialFeatures: 'Ideal for short trips or casual use',
    },
  ];
  
  export default AllRechargePlans;
  